// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjYrvZdwaKf4WJogoKZmhZnEs1owsRJ50',
    appId: '1:948726641069:web:b6122fd2efec08151af124',
    messagingSenderId: '948726641069',
    projectId: 'code-meetings',
    authDomain: 'code-meetings.firebaseapp.com',
    storageBucket: 'code-meetings.appspot.com',
    measurementId: 'G-H6B4WER8LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8e3wDPnCRsvwU1SPeVNshF-gseOSOP_s',
    appId: '1:948726641069:android:5613bcb3a2de95601af124',
    messagingSenderId: '948726641069',
    projectId: 'code-meetings',
    storageBucket: 'code-meetings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeIty5YxBUvsvJzK74el1Tb7JjSQktENc',
    appId: '1:948726641069:ios:fd6c170e01fae8781af124',
    messagingSenderId: '948726641069',
    projectId: 'code-meetings',
    storageBucket: 'code-meetings.appspot.com',
    androidClientId: '948726641069-v55741e97i7f1ibaorthqkojouiustku.apps.googleusercontent.com',
    iosClientId: '948726641069-g8cp5pi0vg9ktc4bko0dllcf9ppabepi.apps.googleusercontent.com',
    iosBundleId: 'ru.fbtw.codeMittingsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeIty5YxBUvsvJzK74el1Tb7JjSQktENc',
    appId: '1:948726641069:ios:fd6c170e01fae8781af124',
    messagingSenderId: '948726641069',
    projectId: 'code-meetings',
    storageBucket: 'code-meetings.appspot.com',
    androidClientId: '948726641069-v55741e97i7f1ibaorthqkojouiustku.apps.googleusercontent.com',
    iosClientId: '948726641069-g8cp5pi0vg9ktc4bko0dllcf9ppabepi.apps.googleusercontent.com',
    iosBundleId: 'ru.fbtw.codeMittingsApp',
  );
}
